### ISSUE TITLE
TypeScript Hero

### ISSUE THREAD

**Issue by michaeljota** [cybertim/vscode-gengetset#37]
#### System information

- OS: Windows 10 AU
- TypeScript Hero version: 0.10.1
- VSCode version: 1.7.2

#### Feature 

There are several features in [TypeScript Hero](https://github.com/buehler/typescript-hero) that are useful, but also other that collides with this. Maybe you could join an develop just one extension? Idk. 

#### Reason

The reason to join would be for us to have one extension that would really help us as developers. 

Cheers!

**Comment by cybertim** [comment]
There are new typescript autoimport/tooling extensions popping up everyday I noticed.. I'd rather see the whole import function being part of the TSserver instead of being something extra in VSCode.

I will take a look at typescript hero too, but do you know if this is capable of auto-import/organize @types and @angular imports? Or does it only handle local stuff? Can't really tell by looking at the github description.

**Comment by michaeljota** [comment]
It is able, and it does it with an autofixing light bulb.

**Comment by cybertim** [comment]
had a short discussion with the maker of typescript hero a while back, maybe in the future (when there is time..) I will try to merge my stuff to typescript hero (since it is using a 'beter' and more future proof way of analysing code).
But since it is so different from this extension (and for now compatible with less older standards + slower with big projects) I'm going to improve my own extension a bit longer (since it is the one I use myself with big projects). 
so, closing the issue for now, but it is noted for the future when the standards (and speed improvements) are there.
