### ISSUE TITLE
Modify the getter setter to not use property setter

### ISSUE THREAD

**Issue by user414** [cybertim/vscode-gengetset#5]
First thanks for the extension, forked it and made the fix in my own repo here

https://github.com/user414/vscode-gengetset/commit/34e3c75ee095e7c473900d44629211ec3b8662c0

All of this is subjective but I tend to agree with basarat here

https://basarat.gitbooks.io/typescript/content/docs/tips/propertySetters.html

for not using property setter but functions. As well I tend to agree with 

http://stackoverflow.com/questions/205853/why-would-a-javascript-variable-start-with-a-dollar-sign

about reserving dollar sign variable in a jquery context. So I slightly modified your extension to generate plain set/get method with the standard variable name, thanks again for the extension.

**Comment by cybertim** [comment]
I agree with these points (coming from real strong typed OO languages) but personally I like the `public get varname` and `public set varname` which can be seen as 'operator overloading' instead of using methods. Even though this introduces the issue of not able to have both the private variables and method names available at the same time, hence the `$` sign i've used to omit the problem when people did not follow my _best practice_ guide which introduces the use of the `_` sign to define their private variables.

I will therefore add this as a feature which can be enabled in the settings for people who dislike the use of the get and set overloading and would like to have the classic getter and setter methods.

I hope you agree :-)

**Comment by user414** [comment]
@cybertim Yes it's quite subjective anyway, with a setting I think it's hard to go wrong.

**Comment by cybertim** [comment]
It's implemented :-)

Disabled by default to not throw the people already using the plugin off-guard.
You can enable it by setting `genGetSet.classic` to `true`
